#!/usr/bin/env bash
#
# Generates the Bun standalone entrypoint used by `bun build --compile`.
#
# `bun build --compile` only embeds assets that are statically imported, and there
# is no flag to include arbitrary files. So this script writes a throwaway entrypoint
# that imports each OpenAPI schema YAML with `{ type: "file" }` (Bun then ships the
# YAML inside the executable), registers the embedded paths on globalThis where
# schemas/index.ts looks for them, and finally runs the normal CLI.
#
# The file is generated (never committed) so the embed list stays in sync with the
# YAMLs on disk and no Bun-specific import syntax leaks into the tsc/ts-node build.
set -euo pipefail

src_dir="packages/test/src"
schema_dir="$src_dir/schemas"
out="$src_dir/.cli-standalone.gen.ts"

imports=""
entries=""
i=0
for f in "$schema_dir"/openapi_v*.yaml; do
  base="$(basename "$f")"                                                  # openapi_v2_3.yaml
  ver="$(echo "$base" | sed -E 's/^openapi_v([0-9]+)_([0-9]+)\.yaml$/\1.\2/')"  # 2.3
  imports="${imports}import schema_${i} from \"./schemas/${base}\" with { type: \"file\" };"$'\n'
  entries="${entries}  \"${ver}\": schema_${i},"$'\n'
  i=$((i + 1))
done

if [ "$i" -eq 0 ]; then
  echo "gen-embed-entry: no schema YAMLs found in $schema_dir" >&2
  exit 1
fi

cat > "$out" <<EOF
// GENERATED by scripts/gen-embed-entry.sh — do not edit, do not commit.
// Standalone Bun binary entrypoint: embeds the OpenAPI schema YAMLs, then runs the CLI.
${imports}
globalThis.__PACT_EMBEDDED_SCHEMA_PATHS = {
${entries}};

// Imported after the global is set so cli.ts's main() can resolve embedded schemas.
await import("./cli");
EOF

echo "gen-embed-entry: wrote $out ($i schema(s) embedded)" >&2
